In [2]:
from geotext import GeoText


In [12]:
places = GeoText("China,London")
len(places.countries)  # 识别文本中的国家

1

In [13]:
import numpy as np

In [17]:
np.linspace(1,1, 100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
from scipy.optimize import curve_fit

In [20]:
def linear_fit(x, a, b): #简单线性拟合
        return a * x + b
fitting_opts = {'maxfev': 800,  # 设置最大迭代次数为1000次
                    }
curve_fit(linear_fit,[1,1], [1,2], p0=[1,1], **fitting_opts)

/var/folders/1f/0cmz51sd34qb2d6lf5tpj1c80000gn/T/ipykernel_13760/1631891213.py:5: OptimizeWarning: Covariance of the parameters could not be estimated
  curve_fit(linear_fit,[1,1], [1,2], p0=[1,1], **fitting_opts)


(array([-99.25, 100.75]),
 array([[inf, inf],
        [inf, inf]]))